"""Seed product data scraped from lebvilleboutique.com (prices in BWP)."""
from datetime import datetime, timezone
import uuid

PRODUCTS = [
    {
        "name": "White Levi Golf T-Shirt",
        "slug": "white-levi-golf-t-shirt",
        "price": 410.00, "compare_at_price": None,
        "category": "clothing", "tag": "bestseller",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ/assets/52f24792-280d-430d-bf0b-e892c31193ec.jpg",
        "description": "A crisp essential. The White Levi Golf Tee balances elevated street ease with timeless tailoring — soft cotton, structured collar, and an effortless drape.",
        "sizes": ["S", "M", "L", "XL"], "stock": 12,
    },
    {
        "name": "Plaid Double-Breasted Blazer",
        "slug": "plaid-double-breasted-blazer",
        "price": 450.00, "compare_at_price": 750.00,
        "category": "clothing", "tag": "clearance",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ%2Fassets%2F2183b0cd-64f7-468b-8441-027f85de0cb8.jpg",
        "description": "Heritage plaid reimagined for the modern woman. Sharp shoulders, hand-finished lapels, and a silhouette designed to command rooms.",
        "sizes": ["S", "M", "L"], "stock": 6,
    },
    {
        "name": "Knit Lounge Two-Piece Suit",
        "slug": "knit-lounge-two-piece-suit",
        "price": 400.00, "compare_at_price": 780.00,
        "category": "clothing", "tag": "clearance",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ%2Fassets%2Ffc3407c4-97a0-4a61-a48b-8b79569a09df.jpg",
        "description": "An indulgent ribbed knit set — for slow Sundays, espresso-bar mornings, and weekend escapes. Tailored to drape, never cling.",
        "sizes": ["S", "M", "L"], "stock": 8,
    },
    {
        "name": "Elegant Black Double-Breasted Coat Dress",
        "slug": "elegant-black-coat-dress",
        "price": 850.00, "compare_at_price": 1200.00,
        "category": "clothing", "tag": "clearance",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ%2Fassets%2F10f361e9-e50a-43d4-8fca-4938f5572efa.jpg",
        "description": "A statement of poised confidence. Structured shoulders, gold-tone buttons, cinched waist — couture energy in everyday silhouette.",
        "sizes": ["S", "M", "L"], "stock": 4,
    },
    {
        "name": "Houndstooth Coat with Faux Fur Trim",
        "slug": "houndstooth-coat-faux-fur",
        "price": 1500.00, "compare_at_price": 2000.00,
        "category": "clothing", "tag": "clearance",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ%2Fassets%2F11679c1b-fc20-43e7-b7b5-5861224785bb.jpg",
        "description": "Old-money tailoring with quiet drama. Wool-blend houndstooth meets plush faux fur cuffs — winter, but rendered in fine art.",
        "sizes": ["M", "L"], "stock": 3,
    },
    {
        "name": "Olive Green Belted Mesh Trench Coat",
        "slug": "olive-green-trench",
        "price": 900.00, "compare_at_price": 1200.00,
        "category": "clothing", "tag": "clearance",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ%2Fassets%2F02350d43-224b-4e15-991a-c6bf58e2dd1b.jpg",
        "description": "Architectural mesh construction in a sun-warmed olive. The kind of coat that turns ordinary corners into editorials.",
        "sizes": ["S", "M", "L"], "stock": 5,
    },
    {
        "name": "Designer Monogram Trench Coat",
        "slug": "designer-monogram-trench",
        "price": 1450.00, "compare_at_price": 2500.00,
        "category": "clothing", "tag": "clearance",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ%2Fassets%2Ff6b24ba2-1ac2-4def-b353-a3477077ff16.jpg",
        "description": "All-over signature monogram, structured belt, double-breasted closure. Iconic, unmistakable, unmistakably yours.",
        "sizes": ["S", "M", "L"], "stock": 2,
    },
    {
        "name": "Sequin Belted Sleeveless Jumpsuit",
        "slug": "sequin-belted-jumpsuit",
        "price": 950.00, "compare_at_price": None,
        "category": "clothing", "tag": "new",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ/assets/6bd64902-601f-41eb-acf8-7d6be24ba945.jpg",
        "description": "Liquid shimmer from shoulder to ankle. The jumpsuit that ends conversations and starts them in the same breath.",
        "sizes": ["S", "M", "L"], "stock": 7,
    },
    {
        "name": "Satin Neck Rushed Split Dress",
        "slug": "satin-neck-split-dress",
        "price": 900.00, "compare_at_price": None,
        "category": "clothing", "tag": "bestseller",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ/assets/66d51b2a-cb95-4c2b-9e23-39f98d731c5b.jpg",
        "description": "Liquid satin, ruched bodice, dangerous slit. Designed to move the way candlelight does.",
        "sizes": ["S", "M", "L"], "stock": 9,
    },
    {
        "name": "U-Neckline Split Blazer",
        "slug": "u-neckline-split-blazer",
        "price": 580.00, "compare_at_price": None,
        "category": "clothing", "tag": "new",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ/assets/c8d774fd-f0da-41b3-b14b-c0a53ff20f50.jpg",
        "description": "Boardroom by day, bottle-service by night. A blazer with a plunging U-neckline and a deep back split.",
        "sizes": ["S", "M", "L"], "stock": 11,
    },
    {
        "name": "Velvet V-Neck Ruffle Plus Size Dress",
        "slug": "velvet-vneck-ruffle-dress",
        "price": 590.00, "compare_at_price": None,
        "category": "clothing", "tag": "new",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ/assets/d6220eaf-e7a4-48ce-93bb-4db21f830175.jpg",
        "description": "Crushed velvet, ruched seams, romantic ruffle hem. Curves cherished, never compressed.",
        "sizes": ["L", "XL", "2XL", "3XL"], "stock": 6,
    },
    {
        "name": "Faux Feather Trim Collar Short Dress",
        "slug": "faux-feather-collar-dress",
        "price": 800.00, "compare_at_price": None,
        "category": "clothing", "tag": "new",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ/assets/9d085a0f-925c-4ca7-9851-c76621848c7d.jpg",
        "description": "A whisper of plumage at the collar. Mini silhouette, maximum drama.",
        "sizes": ["S", "M", "L"], "stock": 5,
    },
    {
        "name": "Sequin V-Neck Mini Wrap Dress",
        "slug": "sequin-vneck-wrap",
        "price": 490.00, "compare_at_price": None,
        "category": "clothing", "tag": "new",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ/assets/853544d8-d005-44c7-899f-11f2dccb872d.jpg",
        "description": "Hand-applied sequins, bias-wrap closure, dance-floor-ready. The little dress that does big things.",
        "sizes": ["S", "M", "L"], "stock": 8,
    },
    {
        "name": "Sequin Wide-Leg Pants",
        "slug": "sequin-wide-leg-pants",
        "price": 590.00, "compare_at_price": None,
        "category": "clothing", "tag": "bestseller",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ/assets/edc5e2da-c010-45ed-aae7-94b26d7dbc34.jpg",
        "description": "Floor-skimming sequin trousers — pair with a silk camisole and quiet confidence.",
        "sizes": ["S", "M", "L"], "stock": 10,
    },
    {
        "name": "HL/SKIN Simply Elegant Lip Gloss",
        "slug": "hlskin-simply-elegant-lipgloss",
        "price": 250.00, "compare_at_price": None,
        "category": "makeup", "tag": "new",
        "image": "/assets/hlskin-lipgloss.png",
        "description": "Mirror-glass shine, never sticky. HL/SKIN signature formula with Vitamin-E for plumper, softer lips.",
        "sizes": ["One Size"], "stock": 24,
    },
    {
        "name": "HL/SKIN Eyeshadow Palette",
        "slug": "hlskin-eyeshadow",
        "price": 350.00, "compare_at_price": None,
        "category": "makeup", "tag": "new",
        "image": "/assets/hlskin-eyeshadow.png",
        "description": "Buttery-blendable pigments in HL/SKIN signature tones. Twelve pans of editorial brilliance.",
        "sizes": ["One Size"], "stock": 30,
    },
    {
        "name": "HL/SKIN Liquid Concealer",
        "slug": "hlskin-liquid-concealer",
        "price": 280.00, "compare_at_price": None,
        "category": "makeup", "tag": "new",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ%2Fassets%2Fa3a73023-c51a-4cd5-b78c-0b71fe0f9f66.jpg",
        "description": "Full-coverage, weightless finish. HL/SKIN advanced blur technology for a flawless editorial look.",
        "sizes": ["Light", "Medium", "Tan", "Deep"], "stock": 22,
    },
    {
        "name": "HL/SKIN Rose Water Wet Wipes",
        "slug": "hlskin-rose-water-wipes",
        "price": 95.00, "compare_at_price": None,
        "category": "skincare", "tag": "new",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ%2Fassets%2Ffbc9265e-e31c-4421-bc7b-a3602a32039e.jpg",
        "description": "Infused with pure Bulgarian rose water. HL/SKIN ritual for instant refreshment.",
        "sizes": ["25 ct"], "stock": 40,
    },
    {
        "name": "HL/SKIN The Fixer Setting Spray",
        "slug": "hlskin-fixer-setting-spray",
        "price": 220.00, "compare_at_price": None,
        "category": "makeup", "tag": "bestseller",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ%2Fassets%2F0d6d9620-6181-453b-b41a-0eeb263c1dbc.jpg",
        "description": "Professional 16-hour hold. The essential HL/SKIN finish for any look.",
        "sizes": ["100ml"], "stock": 28,
    },
    {
        "name": "HL/SKIN Velvet Liquid Lipstick",
        "slug": "hlskin-velvet-liquid-lipstick",
        "price": 320.00, "compare_at_price": None,
        "category": "makeup", "tag": "bestseller",
        "image": "https://cdn.zyrosite.com/cdn-cgi/image/format=auto,w=900,fit=crop,q=100/cdn-ecommerce/store_01K5RZ5ASEMKGQDS7J4CW8SABZ%2Fassets%2F02b10b0b-a351-43d1-9e8d-fb6cc72272c2.jpg",
        "description": "High-pigment, velvet-matte finish. HL/SKIN luxury for your lips.",
        "sizes": ["Rouge", "Mauve", "Cocoa", "Brick"], "stock": 18,
    },

]


def get_seed_products():
    now = datetime.now(timezone.utc).isoformat()
    out = []
    for p in PRODUCTS:
        out.append({
            "id": str(uuid.uuid4()),
            **p,
            "created_at": now,
        })
    return out
